---
title: "Summer Research Project Supplementary Code"
author: "Bernard Miskic"
date: "2025-06-02"
output: pdf_document
---

# Libraries
```{r}
# Here I load many libraries that can be useful
# Note: Only a few of them are needed to run the code below
library(sf)
library(ggplot2)
library(leaflet)
library(missRanger)
library(dplyr)
library(arrow)
library(tidyr)
library(ranger)
library(missForest)
library(magrittr)
library(geojsonio)
library(htmltools)
library(htmlwidgets)
library(stringi)
library(RColorBrewer)
library(ggthemes)
library(tidyverse)
library(ggrepel)
library(dygraphs)
library(xts) 
library(xgboost)
```

# Read in BC shapefiles
```{r}
# use read_sf function to read shapefiles
bc_shape_file = read_sf('/Users/bernardmiskic/Downloads/research_project_meredith/cmaq_boundary_shapefiles/boundary_files_bc/bc_boundary.shp')
```

# Unique Stations
```{r}
Merged_AQS_CSN_2003_2023_BC_Data = read.csv("/Users/bernardmiskic/Downloads/research_project_meredith/Summer Research Project/bc_merged_data/Merged_AQS_CSN_2003_2023_BC_Data.csv")

unique_station_data <- Merged_AQS_CSN_2003_2023_BC_Data |>
               select(Longitude, Latitude, STATION_NAME, EMS_ID) |>
               unique()
```

# Spatial Plotting Data
```{r}
# turn it into an sf object, for spatial plotting
my_sf <- unique_station_data %>% 
  st_as_sf(coords = c('Longitude', 'Latitude')) %>%
  st_set_crs(4326) # using 4326 for lat/lon decimal 

ca_nv_map <- rnaturalearth::ne_states(country = 'Canada', returnclass = 'sf') %>%
  filter(name %in% c("British Columbia", "Alberta"))
```

# Plotting monitor stations
```{r}
ggplot(bc_shape_file) + 
  geom_sf(color = "red") +
  geom_sf(data = my_sf, size = 2) +
  geom_sf(data = ca_nv_map, fill = NA) +
  xlab("Longitude") + ylab("Latitude") 
```


# Spatial Plotting Data (for fire)
```{r}
bc_fire_shapefile_2016 = read_sf("/Users/bernardmiskic/Downloads/research_project_meredith/Fire_Data/Fire_Data_BC/2016_fire_cluster_info_bc.shp")

fire_data_2016 = st_make_valid(bc_fire_shapefile_2016)

centroids_2016 <- st_centroid(fire_data_2016)
```

### Plotting fire points (2016)
```{r}
ggplot(bc_shape_file) +
  geom_sf(color = "red") +
  geom_sf(data = centroids_2016, aes(size = area_km2)) +
  geom_sf(data = ca_nv_map, fill = NA) +
  xlab("Longitude") + ylab("Latitude") +
  labs(title = "Fire Points 2016") +
  theme_minimal() +
  scale_size_continuous(range = c(0.1, 4))  # adjust the size scale if you want
```
